name: espsim

channels:
  - rdkit
  - pytorch
  - psi4
  - conda-forge

dependencies:
  - python>=3.9
  - rdkit
  - pytorch
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - joblib
  - tqdm
  - jupyter
  - py3dmol
  - psi4
  - resp
  - pip
  - pip:
    - git+https://github.com/hesther/chemprop-atom-bond.git
